### ISSUE TITLE
ModuleNotFoundError: No module named 'okada_wrapper.DC3D'

### ISSUE THREAD

**Issue by mradula-vashishtha** [tbenthompson/okada_wrapper#16]
I followed the instructions, cloned the repository and did pip install.. There were no errors. When I try to run the test file given in the wrapper I get this error:

Traceback (most recent call last):
  File "/Users/mradulavashishtha/Documents/anisotropy/strain/okada_wrapper/test_okada.py", line 1, in <module>
    from okada_wrapper import dc3d0wrapper, dc3dwrapper
  File "/Users/mradulavashishtha/Documents/anisotropy/strain/okada_wrapper/okada_wrapper/__init__.py", line 4, in <module>
    from okada_wrapper.okada_wrapper import dc3d0wrapper, dc3dwrapper
  File "/Users/mradulavashishtha/Documents/anisotropy/strain/okada_wrapper/okada_wrapper/okada_wrapper.py", line 1, in <module>
    from .DC3D import dc3d0, dc3d
ModuleNotFoundError: No module named 'okada_wrapper.DC3D'

**Comment by mradula-vashishtha** [comment]
Also am i missing this file #include "fintrf.h"

**Comment by tobiscode** [comment]
See this comment and below: https://github.com/tbenthompson/okada_wrapper/issues/15#issuecomment-2174021431 - TL;DR: it's an issue with the test script and relative imports, if you run the content of the script file manually it should work, as should the library.
